### ISSUE TITLE
Debian Stretch Qt5QuickConfig.cmake

### ISSUE THREAD

**Issue by markd89** [BelledonneCommunications/linphone-desktop#140]
Hi, 

I am trying to build from source so that I can include all codecs (I want G729). 

So I figured out that QT5.9 is not available in Stretch (the current stable Debian), it must come from Sid.

I installed it and dpkg -l shows these:

```
libqt5quick5:amd64                    5.9.2-3                                   
libqt5quickcontrols2-5:amd64          5.9.2-2   
```  

but I am getting this error:
```
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:26 (find_package):
  Could not find a package configuration file provided by "Qt5Quick" with any
  of the following names:

    Qt5QuickConfig.cmake
    qt5quick-config.cmake
```

I searched as root and do not find those files anywhere on the system. 

What am I missing?

Thanks!
Mark

**Comment by traud** [comment]
**Short answer:**
`qtdeclarative5-dev`

**Medium answer:**
In Debian (and Ubuntu), Qt is spread over several packages. When CMake is looking for a specific configuration within Qt, one approach is to
1a) go for <https://www.debian.org/distrib/packages> or
1b) go for <https://packages.ubuntu.com> and then
2) ‘Search the contents of packages’ with `Qt5QuickConfig.cmake`
As you noted already, Linphone Desktop 4 requires at least Qt 5.9 (see [QT_REQUIRE_VERSION](https://github.com/BelledonneCommunications/linphone-desktop/blob/master/src/app/AppController.cpp)). Actually, with a [patch](https://github.com/BelledonneCommunications/linphone-desktop/files/1978944/minimal_version_5_7.txt), even Qt 5.7 and therefore Debian Strech work.

**Long answer:**
Because Qt is spread over several packages in Debian/Ubuntu and because Linphone Desktop 4 requires at least Qt 5.9 (see [QT_REQUIRE_VERSION](https://github.com/BelledonneCommunications/linphone-desktop/blob/master/src/app/AppController.cpp)), you might be better off installing Qt via its installer. This works with even older Debian and Ubuntu releases:
```bash
wget download.qt.io/official_releases/online_installers/qt-unified-linux-x64-online.run
chmod u+x ./qt-unified-linux-*.run
./qt-unified-linux-*.run`
# go for Qt → Qt 5.9.x → Desktop
Qt5_DIR="~/Qt/5.9.6/gcc_64/lib/cmake"
PATH="~/Qt/5.9.6/gcc_64/bin/:$PATH"
```

**Very long answer:**
I am not a team member of Belledonne Communications but just an external contributor. Therefore please, do not take anything for granted but double-check. If you want to build Linphone Desktop 4 yourself much more software packages are required. In Ubuntu 18.04 LTS, I succeeded with these steps:
```bash
sudo apt install autoconf libasound2-dev build-essential libbsd-dev cmake curl doxygen git libglew-dev graphviz libtool default-jre-headless nasm libpcap-dev pkg-config python-pystache python-six libsoci-dev libturbojpeg0-dev libudev-dev libwww-perl libxv-dev yasm libmbedtls-dev libsqlite3-dev libxml2-dev libsrtp2-dev libgsm1-dev libopus-dev libspeexdsp-dev libavcodec-extra libavcodec-dev libswscale-dev libv4l-dev libvpx-dev libantlr3c-dev antlr3 xsdcxx libspandsp-dev libopencore-amrnb-dev libopencore-amrwb-dev libvo-amrwbenc-dev libcodec2-dev
sudo apt install qt5-default qttools5-dev qttools5-dev-tools libqt5svg5-dev libqt5texttospeech5-dev qtdeclarative5-dev qtdeclarative5-dev-tools qtquickcontrols2-5-dev qml-module-qtquick-controls qml-module-qtquick-controls2 qml-module-qtquick-dialogs qml-module-qtqml-models2 qml-module-qtquick-templates2 qml-module-qt-labs-folderlistmodel qml-module-qt-labs-settings qml-module-qt-labs-platform
git clone git://git.linphone.org/linphone-desktop --recursive
cd ./linphone-desktop
./prepare.py --use-system-dependencies --all-codecs --debug
make
gdb ./OUTPUT/desktop/bin/linphone -ex 'run --verbose'
```

**Completely different answer:**
> I want [the audio codec] G729.

For this, you do not have to build Linphone yourself, because the version via [Flatpak](https://flatpak.org/setup/) comes with G.729:
```bash
sudo apt install flatpak
flatpak --user install --from https://linphone.org/flatpak/linphone.flatpakref
flatpak run com.belledonnecommunications.linphone --verbose
```

**Comment by markd89** [comment]
Much, much thanks for posting that!!

I look forward to getting back into this. I'll post back with my results.

**Comment by Wescoeur** [comment]
@traud Thank you for your explanations!

Note: Qt5.9 is required because it exists graphics bugs hard to fix on specific devices with Qt5.7/5.8 with our app.

**Comment by traud** [comment]
@Wescoeur if you find a bug in the Qt Framework, please, document that as detailed as possible. For example, in your source code link to an existing issue report with Qt and/or create an issue report here on GitHub with your project. Then, the community is able to follow-up on that (help, find patches, get latest status). Furthermore, that allows much easier back porting. Personally, I had no issue with Qt 5.7 so far, except for the slider(s) in the volume control dialogue while calling.

I know, you are new to Qt. However, as you see in my patch above, you changed a lot of files to break compatibility with Qt 5.7. Instead, a Qt developer goes for the lowest compatible API number, he is using. Only in the affected file/code, you go for the version you need. If at all. Shall the user fight with the bug, if that is not your bug. That way, one is able to go for an older release much easier/automatically.

Especially for the file `linphone-desktop/ui/scripts/Utils/utils.js`, there was no reason to go for Qt 5.8+ only code. Furthermore, somebody at Belledonne Communications blindly changed all `QtQuick.Controls 2.0` statements to 2.**2**. Only the affected source(s) should have been changed. I would be more than happy if you add (parts) of the patch to your trunk.

**Comment by simwin** [comment]
If you don't want install entire Qt 5.9.x (more than 3 Gb), check this only (350 mb):
[x] Desktop gcc 64bit
[x] Qt Virtual Keyboard 

And then you have to delete the folder ~/Qt/5.9.7/gcc_64/lib/cmake/Qt5TextToSpeech moving to backup, for example:
$mv ~/Qt/5.9.7/gcc_64/lib/cmake/Qt5TextToSpeech ~/backup
And that is enough to make linphone!
