### ISSUE TITLE
Flatpak listing in Flathub

### ISSUE THREAD

**Issue by ovari** [BelledonneCommunications/linphone-desktop#182]
Please list Linphone in Flathub.

Pull requests for new applications to be added https://flathub.org
https://github.com/flathub/flathub

Would the link:
https://linphone.org/flatpak/linphone.flatpakref
need to be converted to:
https://github.com/flathub/org.linphone.Linphone
?

Thank you

**Comment by Wescoeur** [comment]
It's seems a good idea. I have already had a discussion in our team for this. Maybe for the next release.

**Comment by ovari** [comment]
Are you able to advise when your next release is expected? Thank you

**Comment by baimafeima** [comment]
Having a flatpak would be of great benefit: Increase testing area for those unable to compile from source and its potential user base through an easy installation. Hope you'll get a flatpak out.

**Comment by digitalethics** [comment]
Your current flatpak doesn't work. Please consider listing it on Flathub for easy installation. @Wescoeur

**Comment by Wescoeur** [comment]
@digitalethics Sorry, but like I said in an other thread, I stopped working for the company that owns linphone-desktop at least 8 months ago.

**Comment by Francewhoa** [comment]
If needed, both me and the Ubertus.org team would be happy to contribute testing and documentation about Linphone in Flathub repository.

--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---

Below is the same suggestion as above. But with details if you're interested in those.

--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---

## Benefits of Flathub for maintainers:

• All-in-one packages. You save a lot of time. Because Flatpak doesn't depend on outside packages. And Flatpak automatically finds what to bundle using deduplication.

• Single package for all Linux distributions. List of distributions at https://flatpak.org/setup/

• Rapid updates. Your users do not have to wait for packages respiratory to update its list.

• Strong security. Using automated sandbox. With optional override for users of Flatseal.

• Use any repository to your liking. Your own, the https://codeberg.org , GitLab, GitHub, any others. Details at https://docs.flatpak.org/en/latest/publishing.html

• Developer guide at https://docs.flatpak.org/en/latest/

• Free community support for maintainers: 

___• Forum at https://discourse.flathub.org/

___• Instant message at https://matrix.to/#/#flatpak:matrix.org

___• Mailing list at https://lists.freedesktop.org/mailman/listinfo/flatpak

--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---


## Challenge with Flathub:

• Flatpak strength is distribution for desktop applications. Not system level or command line applications. Not yet anyway. Maybe later.

• The first few applications you install use significantly more storage space. Because Flatpak needs to download runtime(s). But those runtimes are downloaded only once and shared with all other applications. This means that on the long term, after installing the first few applications, the storage space used no longer significantly increase.

--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---


## Benefits of Flathub for users:

• Easy and quick installation of the latest free application version at https://flathub.org

• Automatically use any theme to your liking for all apps or selected app. Assuming the app supports theming. This is powered by Flatseal.

___•Steps at https://discourse.flathub.org/t/gtk4-apps-do-not-use-adwaita-dark/1327/2

___•Get Flatseal at https://flathub.org/apps/com.github.tchx84.Flatseal

• Integration with GNOME. You are able to easily install Flatpak applications using the GNOME you're familiar with. When needed, you can still install Flatpak app using https://flathub.org , Terminal, and many other options.

• Of all the packaging options available, Flatpak definitely has the strongest security. Because each application is sanboxed. While at the same time, for some application, the default permissions grant too much access. So users who need strong security need to learn to use Flatseal to adapt the permissions at https://flathub.org/apps/com.github.tchx84.Flatseal

• Freedom. You get more freedom with Flatpak. Because https://flathub.org is controlled by a friendly not-for-profit community of users. In comparison, Snap Store is controlled by the for-profit corporation Canonical. So in the future, under constant pressure from its secret shareholders, when Canonical decides to close Snap Store, you will be in trouble. Not-for-profit community value you the people above profit. There are lots of benefit for you associated with this. Usually, for-profit corporations value money above you, the people. There are lots of risk associated with this.

___• Sources about who controls Flatpak is under "Acknowledgements" title at https://flathub.org/about

___• Sources about who controls Snap Store at https://ubuntu.com/legal/terms-and-policies/snap-store-terms

• Powerful but easy permissions override using this free Flatseal at https://flathub.org/apps/com.github.tchx84.Flatseal
