### ISSUE TITLE
Can not transfer the call between 2 active calls

### ISSUE THREAD

**Issue by Simoneworks** [BelledonneCommunications/linphone-desktop#192]
Hi

with the version Linphone 3.11.1-1-g79a8f90 we can transfer the call between 2 active calls (1 paused  [number 303] and 1 really active [number 101] ).
Like you can see from screenshoots
![transf1](https://user-images.githubusercontent.com/22147362/41539076-26907f46-730d-11e8-8e4e-88dfd8ef105c.PNG)
![transf2](https://user-images.githubusercontent.com/22147362/41539080-2952225c-730d-11e8-99d2-7b3123ea7648.PNG)

Now with the version 4.1.1 we are not able to do that: we need to close the active call [number 101] , take back the paused call [number 303] and transfer it to the other people [from 303 to 101].

With 3.11.1 we can do all with one click, now it is very annoying

Can you restore this usefull function?

Best Regards

**Comment by deepak2503** [comment]
Hi, there can I know the Steps to Compile it for the Windows. As i have earlier tried for Mac OS but using thi ./prepare.py -G Xcode doesn't generate any xcode project file. 
Please let me know if you can help me to compile it for then windows.

**Comment by zahraesm** [comment]
@deepak2503  hi have you been able to comiple it for wndows?? im in major trouble here.

**Comment by shaunjstokes** [comment]
Has there been any progress with this?

The new UI and features in 4.1.1 are excellent but attended transfer is a must have.

Tested on 4.1.1, the attended transfer process as follows is creating a new call on the last step instead of transferring using the existing call:
1) Place call A on hold.
2) Dial the new destination and wait for them to answer (call B).
3) Go back to call A then click transfer to the existing call B (from step 2).

The transferee needs to answer the call again on step 3 which is not typical behaviour and does cause issues with usability particularly in call centre environments.

Effectively what should be an attended transfer becomes a blind transfer, blind transfer does work correctly.

**Comment by polcape** [comment]
Hi, I have the same problem.

Any news on thi issue?

**Comment by MinIsMin** [comment]
Still a serious issue with Desktop 4.1.1-655-g95245907.

Console only outputs
`[0x56004cdbd3d0][Info]"Call transfer init."`
and nothing happens.

**Comment by julonexus** [comment]
Please do not mix issues. I'm closing this one because transfert call work as expected (either if calls are active or not)

**Comment by attermann** [comment]
FYI, I recently submitted pull request #511 which adds support for attended transfer.
