### ISSUE TITLE
No VCARD import or export in linphone 4.1.1

### ISSUE THREAD

**Issue by summerhays** [BelledonneCommunications/linphone-desktop#231]
At least when I use the flatpak version, I don't see any option to import or export vcard contacts. That would be very useful! Thanks! If there's a workaround, that's ok too.

PS I would test building with ENABLE_VCARD but I really am finding it impossible to build this package through the Github clone as you can see from my other errors filed. The submodule thing is just not working right now... Merci de tous vos efforts, je vous félicite pour linphone.

**Comment by Wescoeur** [comment]
Related to #53. Thank you for your message, it's not planned for the moment. But I will try to force this feature in our workflow.

**Comment by Francewhoa** [comment]
Hello @summerhays :) Until this new VCARD import or export feature is added, here are two workarounds: LDAP; Or Manually export & import database.

-------------------

Below is the same message as above. But with details if you're interested in those.

**Option 1: LDAP**

Steps:

   1. Store your contacts into an external LDAP storage. For example, but not limited to, a supplier using [Open-Xchange](https://www.open-xchange.com/) which offers its LDAP feature. For example, some https://Mailbox.org/en/ plans offer this LADP.
   1. Using Linphone, navigate to `Configuration` ---> `Advanced` --->  `LDAP`. Click on the plus button. Configure this form appropriately. 
   1. All your contacts are now displayed within Linphone. If you're not familiar with LDAP, its main benefit is that you can access your contacts in any software which supports LDAP.
   1. Using your LDAP supplier, export or import your contacts to your liking
   1. Linphone will automatically sync. Easy.

-------------------


**Option 2: Manually export & import database**

Steps:

   1. Close Linphone
   1. Backup your Linphone `friends.db` SQLlite database file. For example, on Linux Debian 10 Buster, if your Linphone was installed with the AppImage, then this database is located at `/home/<USERNAME>/.local/share/linphone/friends.db`
   1. Open this `friends.db` database. Manually export the appropriate contact data.
   1. Using the destination Linphone `friends.db` database, manually import your contacts. If you are not familiar with database file. Be careful with the vCard data. You must strictly respect the vCard grammar. Otherwise, the import will fail and there are side effects.
   1. Open Linphone

-------------------

Thanks to alauzon and Wescoeur those workarounds

**Comment by summerhays** [comment]
Thanks so much!

**Comment by abhisheksgsco** [comment]
Anyone knows how i can import bulk contact into Linphone on a Mac
