### ISSUE TITLE
Linphone crashes on Ubuntu 18 after SIP login

### ISSUE THREAD

**Issue by ekasjanov** [BelledonneCommunications/linphone-desktop#250]
After successfull login to my SIP provider(telekom) linphone crashes on Ubuntu 18.04
Linphone version: 4.1.1

Last log lines:
2018-12-12 16:47:54:301 MESSAGE channel [0x5d48350] [995] bytes parsed
2018-12-12 16:47:54:301 MESSAGE Found transaction matching response.
2018-12-12 16:47:54:301 MESSAGE Updating auth context for ream [tel.t-online.de] next nonce is going to be [(null)]

**Comment by XanatosX** [comment]
The same problem happens on Windows 10 with the store and the desktop app.

```
2019-01-08 09:32:54:255 MESSAGE channel [0CBABB30] [1763] bytes parsed
2019-01-08 09:32:54:255 MESSAGE Found transaction matching response.
2019-01-08 09:32:54:255 MESSAGE Updating auth context for ream [tel.t-online.de] next nonce is going to be [(null)]
```

The crashed logged by the system:

```
Name der fehlerhaften Anwendung: linphone.exe, Version: 0.0.0.0, Zeitstempel: 0x5972015d
Name des fehlerhaften Moduls: bellesip.dll, Version: 0.0.0.0, Zeitstempel: 0x5971fe23
Ausnahmecode: 0xc0000005
Fehleroffset: 0x0002b6d3
ID des fehlerhaften Prozesses: 0x1eac
Startzeit der fehlerhaften Anwendung: 0x01d4a72cb7887d76
Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\Linphone\bin\linphone.exe
Pfad des fehlerhaften Moduls: C:\Program Files (x86)\Linphone\bin\bellesip.dll
Berichtskennung: 38b23d5b-375f-43ee-bcba-7acf1c893a65
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:
```

**Comment by MalteHillmann** [comment]
Same problem here. Seems to be a problem with tel.t-online.de?

**Comment by stefan-as** [comment]
Same on Arch Linux using Flatpak, also tel.t-online.de

**Comment by hlg** [comment]
May be related to this  [Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=921266). According to the discussion there, it seems to be fixed in belle-sip with these three commits, but they are not yet in the current linphone-desktop flatpak release:

https://github.com/BelledonneCommunications/belle-sip/commit/7dd8397f0fd24bc3ddf04986488241b1acaf5a94
https://github.com/BelledonneCommunications/belle-sip/commit/3a6a6d677d4dce38f2498be4e10320d8106d76bf
https://github.com/BelledonneCommunications/belle-sip/commit/7191ee1df84707107a7fe4f89d33ebe075a0cb35
