### ISSUE TITLE
Flatpak GPG key has expired

### ISSUE THREAD

**Issue by yann-soubeyrand** [BelledonneCommunications/linphone-desktop#284]
Hi,

The GPG key used for Flatpak has expired yesterday. Can you renew it please?

Regards

**Comment by WPFilmmaker** [comment]
Yes it makes using flatpak update unusable :/

**Comment by dyslesiq** [comment]
Sorry we missed the key expiration. The package will be updated tomorrow.

**Comment by WPFilmmaker** [comment]
@dyslesiq thanks! Also, do you happen to know anything about #197 ?
I see continuous activity in other linphone's repos, but this one seems to be stalled since april, is dev still ongoing? Thank you.

**Comment by dyslesiq** [comment]
A bit later than expected, but the key has been updated!

@WPFilmmaker I commented in #197 about the new release.

**Comment by WPFilmmaker** [comment]
running flatpak update I still got:
F: Error updating remote metadata for 'bc': GPG signatures found, but none are in trusted keyring
F: Warning: Treating remote fetch error as non-fatal since runtime/com.belledonnecommunications.Platform/x86_64/1.6 is already installed: Unable to load summary from remote bc: GPG signatures found, but none are in trusted keyring
F: Warning: Can't find runtime/com.belledonnecommunications.Platform/x86_64/1.6 metadata for dependencies: Unable to load metadata from remote bc: summary fetch error: GPG signatures found, but none are in trusted keyring
F: Warning: Treating remote fetch error as non-fatal since runtime/com.belledonnecommunications.Platform.Locale/x86_64/1.6 is already installed: Unable to load summary from remote bc: GPG signatures found, but none are in trusted keyring
F: Warning: Can't find runtime/com.belledonnecommunications.Platform.Locale/x86_64/1.6 metadata for dependencies: Unable to load metadata from remote bc: summary fetch error: GPG signatures found, but none are in trusted keyring
F: Warning: Treating remote fetch error as non-fatal since app/com.belledonnecommunications.linphone/x86_64/4.1.1 is already installed: Unable to load summary from remote bc: GPG signatures found, but none are in trusted keyring
F: Warning: Can't find app/com.belledonnecommunications.linphone/x86_64/4.1.1 metadata for dependencies: Unable to load metadata from remote bc: summary fetch error: GPG signatures found, but none are in trusted keyring
F: Warning: Treating remote fetch error as non-fatal since app/com.belledonnecommunications.linphone/x86_64/4.0 is already installed: Unable to load summary from remote bc: GPG signatures found, but none are in trusted keyring
F: Warning: Can't find app/com.belledonnecommunications.linphone/x86_64/4.0 metadata for dependencies: Unable to load metadata from remote bc: summary fetch error: GPG signatures found, but none are in trusted keyring

I then unistalled with: flatpak --user remove com.belledonnecommunications.linphone

and then tried to reinstall linphone but I get:
error: Unable to load summary from remote bc: GPG signatures found, but none are in trusted keyring

how do I update the keys?

**Comment by dyslesiq** [comment]
Try to remove the remote: 
`flatpak remote-list`
Then select the linphone-remote
`flatpak remote-delete --force %linphone-remote%`

If you still get the gpg error, try to remove manually:
Edit `~/.local/share/flatpak/repo/config` and remote all linphone remotes

and then: `rm ~/.local/share/flatpak/repo/linphone*.gpg`

**Comment by WPFilmmaker** [comment]
I manually deleted linphon remotes and then ran rm

but now when i try to install I get: Unable to load summary from remote linphone-origin: GPG signatures found, but none are in trusted keyring

:/

**Comment by yann-soubeyrand** [comment]
Thanks for the key update! However I still can't install Linphone, I get the following error:
```
error: Failed to install com.belledonnecommunications.linphone: Error pulling from repo: While pulling app/com.belledonnecommunications.linphone/x86_64/4.1.1 from remote linphone-origin: fsck content object cf41753918b29a0e0d2c99ebdcb7c0dee13425e5789a30210953f7d3b5f5a578: Corrupted file object; checksum expected='cf41753918b29a0e0d2c99ebdcb7c0dee13425e5789a30210953f7d3b5f5a578' actual='ae16ae4e1a21b1cf8fc117b51286f2711f70a98d3eddc85f0374b7119a4d3e24'
```

**Comment by dyslesiq** [comment]
Please post the exact install command you use. I do not reproduce either of those errors here.

**Comment by yann-soubeyrand** [comment]
I use `flatpak install --from https://linphone.org/flatpak/linphone.flatpakref`.

**Comment by WPFilmmaker** [comment]
I used the same command as yann but I get "Unable to load summary from remote linphone-origin: GPG signatures found, but none are in trusted keyring".

**Comment by yann-soubeyrand** [comment]
I confirmed the corruption error on two different computers and two different internet connections.

**Comment by yann-soubeyrand** [comment]
Any news on this @dyslesiq?

**Comment by JesusZapata** [comment]
Hello I try the follow command

```bash
flatpak install --from linphone.flatpakref
```

This command produce the following output

```bash
error: Invalid .flatpakrepo: Key file contains line “<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">” which is not a key-value pair, group, or comment
```
I think the error is related with the GPG signatures

**Comment by yann-soubeyrand** [comment]
Hello,

New error:
```
error: Can't load dependent file https://sdk.gnome.org/gnome.flatpakrepoServer returned status 404: Not Found
```

Maybe flathub should be used instead of sdk.gnome.org for the runtime?

**Comment by WPFilmmaker** [comment]
+1 for flathub as it would give visibility to the project as well. AFAIK maintenance is done by flathub volounteers but I think it would be no prob if belledonne did the maintenance.

**Comment by saulmayo** [comment]
+1 Any news?

Execute:
`flatpak install --from https://linphone.org/flatpak/linphone.flatpakref`

Response message: 
`error: Invalid .flatpakrepo: El archivo de claves contiene la línea «<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">» que no es un par valor-clave, grupo o comentario`

**Comment by dyslesiq** [comment]
I have updated the runtime repo to use flathub instead.

I did reproduce the error `Key file contains line “<!DOCTYPE HTML PUBLIC "-//` with an older version of flatpak (0.8, from debian oldstable).`

But when I ran the exact same command again, the error was gone and the installation was successful...

Looking at the different problems we have with flatpak, the inconsistencies at installation and run time plus the maintainability cost of the build, we are seriously considering dropping flatpak in favor of AppImage.

**Comment by cognifloyd** [comment]
The flatpak binaries need to be rebuilt with the new key. Even if there's not a new release, could someone rebuild the flatpak with the new key? They won't install because the key doesn't match.
