### ISSUE TITLE
Call history still not working in newest beta Linphone-4.2.0-alpha.63+59c4cc1

### ISSUE THREAD

**Issue by JohnHughesAtlantech** [BelledonneCommunications/linphone-desktop#377]
To start with a clean history I delete .local/share/linphone/call-history.db

I start linphone, nothing in "previously" pane, as I expect.

I receive an incoming call from my mobile.  The call works,  but there is still nothing in "previously".

The call_history table shows my incoming call:

1|"John Hughes [CALVAEDI]" <sip:+33xxxxxxx@10.27.128.1>|<sip:john@10.27.128.3;transport=udp>|1|9|1591256162|1591256164|0|0|4.991184|02e0d88b09641a337625b9080f93c47a@10.27.128.1:5060|

I make an outgoing call from linphone to my mobile.

Now the "previously" shows my mobile number, and when I click on it for the detail I see the outgoing call but not the first incoming call.

call_history contains:

1|"John Hughes [CALVAEDI]" <sip:+33xxxxxxxx@10.27.128.1>|<sip:john@10.27.128.3;transport=udp>|1|9|1591256162|1591256164|0|0|4.991184|02e0d88b09641a337625b9080f93c47a@10.27.128.1:5060|
2|sip:john@10.27.128.1|sip:+33xxxxxxxx@10.27.128.1|0|4|1591256363|1591256370|0|0|4.248732|bhrbYlUZEx|

If I make *another* inbound call then I see the first outbound call and the second inbound call in the detailed history, but still not the first inbound call.

call_history now has:

1|"John Hughes [CALVAEDI]" <sip:+33xxxxxxxxx@10.27.128.1>|<sip:john@10.27.128.3;transport=udp>|1|9|1591256162|1591256164|0|0|4.991184|02e0d88b09641a337625b9080f93c47a@10.27.128.1:5060|
2|sip:john@10.27.128.1|sip:+33xxxxxxxxx@10.27.128.1|0|4|1591256363|1591256370|0|0|4.248732|bhrbYlUZEx|
3|"John Hughes [CALVAEDI]" <sip:+33xxxxxxxxx@10.27.128.1>|<sip:john@10.27.128.3;transport=udp>|1|8|1591256589|1591256591|0|0|4.991421|0bfc258e266bd1744f74571320f52e98@10.27.128.1:5060|

I quit linphone and restart it.  The detailed history for my phone number **only shows the outbound call**.  There is no trace of either of the inbound calls.

The call_history table still contains details of all the calls.

Exact version I was testing:

https://www.linphone.org/snapshots/AppImages/Linphone-4.2.0-alpha.63+59c4cc1.AppImage

**Comment by julonexus** [comment]
You received your call to @10.27.128.3 and send call from @10.27.128.1
These are 2 differents accouts. I guess you selected the @10.27.128.1 from the top-left area in the main window. It is why you only get outbound calls.

**Comment by JohnHughesAtlantech** [comment]
On 04/06/2020 10:05, Julien Wadel wrote:
>
> You received your call to @10.27.128.3 and send call from @10.27.128.1
> These are 2 differents accouts. I guess you selected the @10.27.128.1 
> from the top-left area in the main window. It is why you only get 
> outbound calls.
>

10.27.128.1 is the proxy (asterisk)

10.27.128.3 is the machine linphone is running on (the address is 
dynamically allocated, it won't always be the same).

The "default identity" that linphone has made for me is:

"John HUGHES" <sip:john@[2a01:cb08:256:3d00:9c67:73a1:789f:9ee7]:5060> (!)

I find the whole proxy/account set-up in linphone totally confusing.

Also, it's not that I only get outbound calls.  I *do* get inbound 
calls, if:

1. I have already made an outbound call to that number, and

2. The inbound call is in the same linphone session.

**Comment by glebaccon** [comment]
There is clearly a problem with default identity and real SIP account. For me all inbound calls come from the SIP account (build with the server IP address) and not the default identity (build with local IP address).

I think Linphone understand only the default identity (the local address) to display the history.

**Comment by julonexus** [comment]
The default identity is used mainly for testing and should not be used as a real account. It is not fully featured.
@JohnHughesAtlantech Could you confirm that you have your issue on a real account?

**Comment by JohnHughesAtlantech** [comment]
On 12/06/2020 17:07, Julien Wadel wrote:
>
> The default identity is used mainly for testing and should not be used 
> as a real account. It is not fully featured.
> @JohnHughesAtlantech <https://github.com/JohnHughesAtlantech> Could 
> you confirm that you have your issue on a real account?
>
I don't use the default identity (I don't know what it's for).

I have my laptop, connected to the asterisk system by a vpn.

The laptop's IP is (checks notes) 10.27.128.3, but that is not fixed.

The asterisk system is 10.27.128.1

I REGISTER with the asterisk system as sip:john@10.27.128.1

**Comment by julonexus** [comment]
When you are sending and receiving messages, what are your adresses? I suspect a different behaviour between call and messages when logging from the SDK.

**Comment by julonexus** [comment]
When you are sending and receiving messages, what are your addresses in the log? I'm suspecting a different behaviour between call and messages when logging from the SDK. Messages should be fine but not calls

**Comment by glebaccon** [comment]
Same for me.

My client address is 192.168.1.101
My asterisk server is 192.168.1.231

When I receive calls the callee (in call-history.db) is sip:xxx@192.168.1.101
When I call someone the callee is sip:xxx@192.168.1.231

So, in my history I see only the outgoing calls.

**Comment by nemeziiz** [comment]
I have exactly the same problem
please help me

**Comment by julonexus** [comment]
@nemeziiz Use a real sip provider like antisip or linphone if you don't want issues.

**Comment by abesherman** [comment]
I am having the same issues using voip.ms Please help.

**Comment by ziggystar** [comment]
I'm sharing my problem here, too. I do not see incoming calls, and I assume this is because linphone is unable to match the identities, although it knows that I have received the call on a certain identity. You should add a column where you store the account that received the call (and not what you get from the SIP server).
![image](https://user-images.githubusercontent.com/459632/93301411-b04ce180-f7f8-11ea-90a0-2f1111c1c847.png)

After I created a new account with `<sip:134@192.168.63.18:41863;transport=udp>` I could see all the incoming calls from my original account. But of course not the outgoing ones. As a fix, I will copy over the rows in the DB and use the new account.
But this should really be fixed properly. Doing some funny string matching on this string is bound to not work, because the string is not generated by linphone, but comes from outside. And you cannot count on what other programs do.

**Comment by julonexus** [comment]
"matching on this string is bound to not work, because the string is not generated by linphone". Your provider send what it want, Linphone do with what it get. All fields of INVITE comes from your provider but some are respectful against RFC.
When you receive the call, this is not your account but your application that receive it. It's why you get the call. Do you understand the difference? The matching is done by parsing the INVITE sent by your provider.
There is a workaround when you have only one account (by doing an implicit match) but not with multi-account.

A SIP address is in the form of sip:name@domain. Having an IP and DNS as a domain is having 2 different addresses, so 2 different accounts.
From the RFC, a user identifies himself by the SUBSCRIBE. TO must used to identify users, not the device. Why setting funny stuff on this field then? "Not counting on what other programs do" is the point of following RFC. We don't have enough human resource to take account all cases that doesn't respect rules.

**Comment by julonexus** [comment]
The issue doesn't come from Linphone but from provider where the identity field doesn't match to the subscribed account.
A workaround has been done to show all call logs by clicking on the "previously" bar. It will be available in the next nightly from this [commit](8ecd1bc32c3f251b19b7b0f8425cb626aa1f5e15)
As long as you can get your incoming call, I'm closing this issue. Thank you all for you feedbacks.
