### ISSUE TITLE
Microphone doesn't work in Linphone Desktop Windows version.

### ISSUE THREAD

**Issue by suchagoodguy** [BelledonneCommunications/linphone-desktop#477]
OS: Windows 7 x64, Windows 10 1909, 20H2
Version: 4.3.0-alpha.76+6f63b37c-win32
Microphone works for other applications but does not for Linphone.
By the way in version 4.2.5-win32 microphone works, but russian Caller-IDs look wrong codepage.
Such behavior was detected at 4 computers.

**Comment by adlerweb** [comment]
Since my issue seems similar I'll add my opservations here.

System: Win 10 20H2 Pro x64 DE
Linphone Desktop **4.2.5** win32, **4.1.1** and **4.3.0-alpha.85**+77a3f294-win32

**Problem**: In settings I see all devices as WASAPI recording options, however none of them show any indication of incoming Sound. Capture level stays at 0 without any movement, looks like the channels are muted. The microphone itself is not muted and works in other software using WASAPI (for example mumble or Jitsi desktop). Playback in linphone works fine.

I noticed Linphone isn't listed in Privacy -> Microphone as Desktop app using the microphone while the working ones are, so I guess this might be a problem with the way Linphone tries to request microphone permissions from the OS. I saw something about asking for microphone permissions on a [Linphone GitLab](https://gitlab.linphone.org/BC/public/linphone-windows10#application-permissions) regarding the store app, however I haven't seen any requests (these are afair only for Apps anyways) and the GPO mentioned isn't listed in my version of W10.

@suchagoodguy Do you observe the same behaviour (Device listed, no capture level)? Is your system listing the linphone 4.3 alpha exe and/or 4.2.5 exe in privacy settings? Are you also running a non english windows version?

**@ people with working microphones on W10:** Is linphone listed as app using the microphone in Settings->Pricacy->Microphone->Desktop Apps? Is your capture level bar working? Are you using an english or non-english version of windows?

**@ devs:** any idea on how to force linphone to request permissions?

**Comment by suchagoodguy** [comment]
Yes, we have Russian-edition of Windows.
Devices are listed, but linphone can't use microphone.

**Comment by julonexus** [comment]
Hi
Your logs show :
`2021-04-13 13:35:14:112 [/bctbx] ERROR Could not initialize the MSWASAPI audio input interface [80070057]`
So your mic cannot be used. You have to check this error (80070057) on WASAPI.

This is the result of IAudioClient->Initialize (or IAudioClient2->Initialize). I guess it is about of sharing the device that cannot be shared (AUDCLNT_SHAREMODE_SHARED mode)

Some advices on internet lead to:
"Settings in Windows 10 - Privacy - Microphone (left menu) - "Allow apps to access your microphone" ON"
or:
"adding my windows service to exception of Kaspersky Antivirus application"

**Comment by julonexus** [comment]
No more feedback, I guess it is resolved.
