### ISSUE TITLE
No H.264 for linux desktop?

### ISSUE THREAD

**Issue by etamme** [BelledonneCommunications/linphone-desktop#51]
I only see VP8 as a video option for linux desktop, but apparently it is available for other os's

**Comment by ghismary** [comment]
We cannot distribute an app with H.264 due to licensing issues. In the case of Mac OS X we are using the hardware accelerated API for which you have already paid the license fee when buying your Apple device, and for Windows we are downloading the openh264 library from Cisco during the installation process, and in this case this is Cisco that already paid the license fee. But for GNU/Linux, this is not possible therefore H.264 is not available... unless you build it yourself with H.264 support activated.
