### ISSUE TITLE
Request: add option to disable builtin updater

### ISSUE THREAD

**Issue by sjaeckel** [BelledonneCommunications/linphone-desktop#561]
When installing `linphone` via e.g. the Arch User Repositories [0] the builtin updater will not be used as it would clash with the way how one manages their distribution.

Therefor it would be helpful if there were a way to disable the builtin version check.

A compile-time switch would not be sufficient as I'm still installing the AppImage version, i.e. it should (also) be a runtime switch.

FTR: I've tried to search for where this happens but ended up at `onVersionUpdateCheckResultReceived()` where I didn't find out yet how this is called ... I guess I'd have to setup the entire build environment to properly try further, but time ...

[0] https://aur.archlinux.org/packages/linphone-desktop-appimage/

**Comment by julonexus** [comment]
Options for update checking have been added.
https://gitlab.linphone.org/BC/public/linphone-desktop/-/commit/4814eed85d3dd08d5658bd4058e640b0ea001c27

**Comment by sjaeckel** [comment]
wow, that was quick!

thanks a lot :)

**Comment by doctorevil30564** [comment]
Sorry to revive a dead topic, but I wanted to confirm something about this. If I use the command switch above:
-DENABLE_UPDATE_CHECK=OFF, this switch turns on a menu option in the linphone AppImage?

If so how would I be able to then edit the code so that this menu option always returns as being disabled if someone tries to turn it on with this option.

I have a custom version that we use in our call center that has the close app on window close, and auto-answer options permanently turned on. We don't want the update notifications popping up on the workstations when the call center agents are taking calls, as we get flooded with tickets for it. I need to be able to control how updates are pushed out, as we use Ansible to do this when we need to update the Linphone AppImage.
