### ISSUE TITLE
little window to answer call sometimes completly black

### ISSUE THREAD

**Issue by AlBundy33** [BelledonneCommunications/linphone-desktop#819]
On Windows 10 it happens from time to time that on an incoming call the little window in the lower right corner to accept or reject the call is completly black.

If you know where the buttons are, it is still possible to click them and accept/reject the call.

This issue does not occur very often but is very annoying when it does.

Is this a known issue and does anybody know a workaround?

**Comment by julonexus** [comment]
Hi, 
Sometimes, Qt cannot render graphics. That's random...
- to know who is calling, you can check the call logs by clicking on the call logs button to force refresh(5.2.3 will have a fix on refreshing).
- to accept/reject, you can use keyboard shortcuts (since 5.2.2). The application must be focused:
1) 'Ctrl+Shift+W' (or V): accept with video the last incoming call.
2) 'Ctrl+Shift+A': accept without video the last incoming call.
3) 'Ctrl+Shift+D': terminate the last call.
Regards

**Comment by Ledjlale** [comment]
That's not a final solution but a workaround for an unexpected case as there is no solution.
You have to wait for the 6.0 where notifications are embedded to the application

**Comment by AlBundy33** [comment]
Sounds interesting - can I download Linphone 6 somewhere?

**Comment by AlBundy33** [comment]
@julonexus @Ledjlale can I download Linphone 6.0 somewehre to test?
